version: '3'

services:
  db:
    restart: always
    build: ./db
    hostname: db
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"

  web:
    build: ./web
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
      FLASK_RUN_HOST: 0.0.0.0
    ports:
     - "5000:5000"
    volumes:
     - ./web:/code
